language: ruby
script: "bundle exec rake test"

cache:
  - bundler
before_cache:
  - rm -f ${BUNDLE_PATH}/**/extensions/**/{gem_make.out,mkmf.log}

rvm:
  - 2.5.7
  - 2.6.5
  - 2.7.0
  - ruby-head
  - jruby-9.2.8.0
gemfile:
  - gemfiles/active_record_52.gemfile
  - gemfiles/active_record_60.gemfile
  - gemfiles/active_record_edge.gemfile

jobs:
  allow_failures:
    - gemfile: gemfiles/active_record_edge.gemfile
    - rvm: ruby-head
  include:
    - rvm: 2.4.9
      gemfile: gemfiles/active_record_52.gemfile
    - stage: rubocop
      script: bundle exec rake rubocop
      rvm: 2.6.5
  fast_finish: true

branches:
  only:
    - master
